名称：生成MopClient

在……之上：
推：
分支：[主要的]
工作流程分派(_D)：

作业：
建立：
run-on:ubuntu-latest

步骤：
-名称：签出存储库
用途：操作/签出@v3

-名称：设置JDK17
用法：操作/setup-java@v3
和……一起：
java版本："17"
分布：'temurin'

-名称：授予渐变包装器权限
运行：chmod+x./gradlew

-名称：生成MopClient广口瓶
运行：./gradlew生成--无守护程序

-名称：将jar上传为工件
用法：操作/上载工件@v3
和……一起：
名称：MopClient-jar
路径：build/libs/MopClient-1.0.0.jar
